home:
  centroid:
    x: 0.038
    y: 4.49
  orientation:
    w: 0.707
    z: 0.707
  vertices:
  - x: 0.038
    y: 4.49
  - x: 0.038
    y: 4.49
  - x: 0.038
    y: 4.49
  - x: 0.038
    y: 4.49
kitchen:
  centroid:
    x: 1.43
    y: 5.39
  orientation:
    w: 0.707
    z: 0.707
  vertices:
  - x: 1.43
    y: 5.39
  - x: 1.43
    y: 5.39
  - x: 1.43
    y: 5.39
  - x: 1.43
    y: 5.39
office:
  centroid:
    x: 2.78
    y: 4.00
  orientation:
    w: 0.707
    z: 0.707
  vertices:
  - x: 2.78
    y: 4.00
  - x: 2.78
    y: 4.00
  - x: 2.78
    y: 4.00
  - x: 2.78
    y: 4.00
  
